version: "3"

services:
  eventstore:
    image: eventstore/eventstore:20.6.1-buster-slim
    volumes:
      - eventstore-data:/var/lib/eventstore
    env_file:
      - eventstore-20.6/service.env
      - ../.env/eventstore-20.6.env
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      - devsvcnet

volumes:
  eventstore-data:
    driver: local
